import dotenv from "dotenv";

dotenv.config();

const PORT = process.env.PORT || 5000;
const MODE = process.env.MODE;
const MONGO_URI = process.env.MONGO_URI;
const WHITELIST_URLS = process.env.WHITELIST_URLS
  ? process.env.WHITELIST_URLS.replace(/[\[\]\s]/g, "").split(",")
  : [];
const NODEMAILER_PASS = process.env.NODEMAILER_PASS;
const NODEMAILER_FROM_EMAIL = process.env.NODEMAILER_FROM_EMAIL;
const uniqueNanoIdLength = process.env.UNIQUE_NANOID_LENGTH || 8;
const JWT_TOKEN_NAME = process.env.JWT_TOKEN_NAME;
const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY;
const SESSION_SECRET_KEY = process.env.SESSION_SECRET_KEY
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET;
const BCRYPT_SALT_ROUND = process.env.BCRYPT_SALT_ROUND;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_CLOUD_SECRET = process.env.CLOUDINARY_CLOUD_SECRET;
const CLOUDINARY_CLOUD_URL = process.env.CLOUDINARY_CLOUD_URL;
const CLIENT_URI = MODE === 'production' ? "" : "http://localhost:5173"

export { PORT, MODE, MONGO_URI, WHITELIST_URLS ,NODEMAILER_PASS,NODEMAILER_FROM_EMAIL, uniqueNanoIdLength , JWT_TOKEN_NAME,JWT_SECRET_KEY,SESSION_SECRET_KEY,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,BCRYPT_SALT_ROUND,CLOUDINARY_CLOUD_SECRET,CLOUDINARY_CLOUD_URL,CLOUDINARY_API_KEY,CLIENT_URI};